pipeline {
    agent any
    environment {
        PLAYBOOK = 'workloads/run_workloads.yaml'
        PROMETHEUS = 'http://100.64.176.12:9090'
        BUILD_COMMIT = "${GIT_COMMIT}"
        EXTRA_ANSIBLE_PARAMS = ""
        LABELS = "{additional_labels: {build_number: \"${BUILD_NUMBER}\", build_node_name: \"${NODE_NAME}\", build_commit: \"${GIT_COMMIT}\"}}"
		TAGS = ""
		RUN_WORKLOADS_SLEEP_TIME = 300
    }
    stages {
        stage('Build pex') {
            stages {
                stage("Prepare venv && build pex") {
                    steps {
                        sh('make venv')
                        sh('make check')
                        sh('make wca_package')
                    }
                }
            }
        }
        stage('Kubernetes') {
            agent { label 'kubernetes' }
            environment {
                INVENTORY='tests/e2e/demo_scenarios/common/inventory-kubernetes.yaml'
                KUBERNETES_HOST='100.64.176.34'
                CRT_PATH = '/etc/kubernetes/ssl/'
                CONFIG = 'wca_config_kubernetes.yaml'
            }
            steps {
                print('Reconfiguring wca...')
                copy_config(env.CONFIG)
                replace_in_config()
                start_wca()
				run_workloads(env.TAGS)
            }
        }

        stage('Mesos') {
            agent { label 'mesos' }
            environment {
                INVENTORY='tests/e2e/demo_scenarios/common/inventory-mesos.yaml'
                MESOS_MASTER_HOST='100.64.176.23'
                CONFIG = 'wca_config_mesos.yaml'
            }
            steps {
                print('Reconfiguring wca...')
                copy_config(env.CONFIG)
                replacce_in_config()
                start_wca()
				run_workloads(env.TAGS)
            }
        }
    }
}

def copy_config(config) {
    sh "sudo cp ${WORKSPACE}/tests/e2e/demo_scenarios/common/${config} ${WORKSPACE}/prm/demo_scenarios/common/wca_config.yml.tmp"
}

def replace_in_config() {
    contentReplace(
        configs: [
            fileContentReplaceConfig(
                configs: [
                    fileContentReplaceItemConfig( search: 'BUILD_COMMIT', replace: "${GIT_COMMIT}", matchCount: 0),
                    fileContentReplaceItemConfig( search: 'BUILD_NUMBER', replace: "${BUILD_NUMBER}", matchCount: 0),
                    fileContentReplaceItemConfig( search: 'CRT_PATH', replace: "${CRT_PATH}", matchCount: 0)
                ],
                fileEncoding: 'UTF-8',
                filePath: "${WORKSPACE}/tests/e2e/demo_scenarios/common/wca_config.yml.tmp")])
}

def copy_ready_config() {
    sh'''
    sudo cp ${WORKSPACE}/tests/e2e/demo_scenarios/commom/wca_config.yml.tmp /etc/wca/wca_config.yml
    sudo cp ${WORKSPACE}/dist/wca-prm.pex /usr/bin/wca.pex
    '''
}

def start_wca() {
    sh "systemctl restart wca"
    sleep 5
    sh "systemctl status wca"
}

def run_workloads(tags) {
    dir('workloads') {
        echo 'Start workloads'
        sh "ansible-playbook ${EXTRA_ANSIBLE_PARAMS} -i ${WORKSPACE}/demo_scenarios/run_workloads/inventory.yaml --tags=${tags} -e \"${LABELS}\" ${WORKSPACE}/${PLAYBOOK}"
    }
}

def stop_workloads() {
   echo 'Stop all workloads...'
   sh 'ansible-playbook  ${EXTRA_ANSIBLE_PARAMS}  -i ${WORKSPACE}/${INVENTORY} --tags=clean_jobs ${WORKSPACE}/${PLAYBOOK}'
   sleep 5 
}
